### ISSUE TITLE
DC_script.py fails at step 6 and 7

### ISSUE THREAD

**Issue by teuben** [teuben/dc2019#21]
This is the new "python3only" branch (although the casa5 version also does it).  Steps 0-5 all work.

In **step-6** I get:

SEVERE  SynthesisImagerVi2::defineImage (file casa-source/code/synthesis/ImagerObjects/SynthesisImagerVi2.cc, line 594) Error in building Coordinate System and Image Shape : 2021-04-30 13:22:02       SEVERE  MSTransformRegridder::calcChanFreqs     calcChanFreqs failed, check input start and width parameters

In **step-7** I get this:

Table    .../scripts4paper/tmp/skymodel-c_120L.sd.SD_ro_TPfac1000000.0.ms does not exist

**Comment by emoravec** [comment]
I also get the same error at step 6 running DC_script.py from the 'python3only' branch.

**Comment by LydiaMF** [comment]
**step6:** Can it be that mode (in the *par*-file) is set to 'cube' instead of 'mfs' for the skymodel-data? see Emily's error message on slack-channel #testing

**step7:** Oh my gosh, I'm crying and dying from laughing. I switched the create_TP2VIS_ms and transform_INT_to_SD_Freq_spec off to save time once they were created in the first run. If you uncomment these code blocks, it works.

**Comment by LydiaMF** [comment]
**step6:** I was able to reproduce it. This happens when you use the channel setup from M100 for the simulated cont data.  Use mode='mfs' and any channel setup will be ignored.
